[project]
name = "expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "authlib>=1.6.5",
    "dotenv>=0.9.9",
    "streamlit>=1.51.0",
    "supabase>=2.22.3",
]
